"""Recording subsystem — .tmu file format with integrity verification."""

from telemu.recording.tmu_format import (
    CHANNEL_DEF_SIZE,
    FOOTER_SIZE,
    FORMAT_VERSION,
    HEADER_FIXED_SIZE,
    MAGIC,
    ChannelDef,
    ChannelType,
    TMUCorruptionError,
    TMUFooter,
    TMUHeader,
    VerifyResult,
    build_minimal_tmu,
    compute_channel_offsets,
    frame_payload_size,
    pack_frame,
    repair_file,
    repair_tmu,
    unpack_frame,
    verify_file,
    verify_tmu,
)

__all__ = [
    "CHANNEL_DEF_SIZE",
    "FOOTER_SIZE",
    "FORMAT_VERSION",
    "HEADER_FIXED_SIZE",
    "MAGIC",
    "ChannelDef",
    "ChannelType",
    "TMUCorruptionError",
    "TMUFooter",
    "TMUHeader",
    "VerifyResult",
    "build_minimal_tmu",
    "compute_channel_offsets",
    "frame_payload_size",
    "pack_frame",
    "repair_file",
    "repair_tmu",
    "unpack_frame",
    "verify_file",
    "verify_tmu",
]
